POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0Y2U5NGM4NzgzNGM5MTRmYjU2MjYyMyIsImlhdCI6MTY5MTM0MzA2Nn0.fjJ6euSqARGIimClJbTMIcst6COoH71TgEvYedp4f7k

{
  "title": "Im logged in",
  "author": "me",
  "url": "String12",
  "likes": 2220952340958
}